# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: EASY CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: npm install, build
        run: 
          npm i    
          npm run build
          echo "这样执行"
          git config --global user.email "tangjian1891@163.com"
          git config --global user.name "tangjian1891"
          git add ./
          git commit -m 'deploy'
          git push https://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@github.com/tangjian1891/docs.git
        env:
         CI: true
  
# echo $(pwd)   /home/runner/work/docs/docs
